import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "./font/Roboto-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/Roboto-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./font/Roboto-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./font/Roboto-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
